MODEL:
  TYPE: st
  NAME: StructuralTransformer8422
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: None
  SWIN:
      FINAL_UPSAMPLE: "expand_first"
      EMBED_DIM: 96
      DEPTHS: [ 8, 4, 2, 2 ]
      DECODER_DEPTHS: [ 8, 4, 2, 2 ]
      NUM_HEADS: [ 3, 6, 12, 24 ]
      WINDOW_SIZE: 7
